In [15]:
import pandas as pd
from IPython.display import display

In [4]:
df= pd.read_csv("Orders.csv")

In [5]:
df.head

<bound method NDFrame.head of     Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]>

In [6]:
df.tail

<bound method NDFrame.tail of     Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]>

In [7]:
df.info

<bound method DataFrame.info of     Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]>

In [8]:
df.describe

<bound method NDFrame.describe of     Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]>

In [11]:
pd.set_option('display.max_rows',None)

In [12]:
pd.set_option('display.max_columns',None)

In [19]:
print(df)

    Order ID  Order Date  CustomerName              State                City
0    B-26055  10-03-2018     Harivansh      Uttar Pradesh             Mathura
1    B-25993  03-02-2018        Madhav              Delhi               Delhi
2    B-25973  24-01-2018   Madan Mohan      Uttar Pradesh             Mathura
3    B-25923  27-12-2018         Gopal        Maharashtra              Mumbai
4    B-25757  21-08-2018      Vishakha     Madhya Pradesh              Indore
5    B-25967  21-01-2018        Sudevi      Uttar Pradesh           Prayagraj
6    B-25955  16-01-2018         Shiva        Maharashtra                Pune
7    B-26093  27-03-2018        Sarita        Maharashtra                Pune
8    B-25798  01-10-2018        Shishu     Andhra Pradesh           Hyderabad
9    B-25602  01-04-2018        Vrinda        Maharashtra                Pune
10   B-25858  13-11-2018        Uudhav        Maharashtra              Mumbai
11   B-25969  21-01-2018      Shreyshi            Gujarat               Surat
12   B-26099  30-03-2018        Bhishm        Maharashtra              Mumbai
13   B-25997  04-02-2018        Yogesh        Maharashtra                Pune
14   B-25881  25-11-2018        Lalita      Uttar Pradesh             Mathura
15   B-25761  25-08-2018        Madhav      Uttar Pradesh             Mathura
16   B-25887  01-12-2018      Vishakha      Uttar Pradesh           Prayagraj
17   B-25823  18-10-2018         Rohan        Maharashtra              Mumbai
18   B-25853  08-11-2018        Gaurav            Gujarat           Ahmedabad
19   B-25862  15-11-2018          Amol              Bihar               Patna
20   B-25830  26-10-2018        Aastha   Himachal Pradesh               Simla
21   B-25786  19-09-2018   Madan Mohan      Uttar Pradesh             Mathura
22   B-25686  11-06-2018         Pooja   Himachal Pradesh               Simla
23   B-26022  18-02-2018     Shrichand             Punjab          Chandigarh
24   B-26003  08-02-2018        Hitesh     Madhya Pradesh              Bhopal
25   B-25755  19-08-2018       Shourya            Kerala   Thiruvananthapuram
26   B-25902  10-12-2018      Ishpreet        Maharashtra              Mumbai
27   B-25935  04-01-2018        Sudhir           Nagaland              Kohima
28   B-25797  30-09-2018       Sauptik     Madhya Pradesh              Indore
29   B-25639  27-04-2018         Lisha     Madhya Pradesh              Bhopal
30   B-25681  04-06-2018        Bhawna     Madhya Pradesh              Indore
31   B-25909  13-12-2018         Sujay        Maharashtra                Pune
32   B-25910  14-12-2018           Jay              Delhi               Delhi
33   B-25950  13-01-2018        Shruti     Madhya Pradesh              Indore
34   B-25613  12-04-2018         Mohan            Haryana          Chandigarh
35   B-25919  23-12-2018          Neha          Rajasthan             Udaipur
36   B-25768  01-09-2018     Shreyoshe          Karnataka           Bangalore
37   B-25629  24-04-2018        Hemant            Kerala   Thiruvananthapuram
38   B-25729  22-07-2018     Madhulika     Madhya Pradesh              Bhopal
39   B-25943  09-01-2018       Shardul            Gujarat           Ahmedabad
40   B-25842  02-11-2018       Sheetal        Maharashtra                Pune
41   B-26073  21-03-2018    Pournamasi     Madhya Pradesh              Indore
42   B-25778  11-09-2018       Surabhi        Maharashtra              Mumbai
43   B-25717  12-07-2018       Manshul      Uttar Pradesh             Lucknow
44   B-26085  26-03-2018     Shrichand             Punjab          Chandigarh
45   B-26048  04-03-2018         Parth        Maharashtra                Pune
46   B-25793  24-09-2018     Siddharth     Madhya Pradesh              Indore
47   B-25656  11-05-2018      Priyanka        Maharashtra                Pune
48   B-25608  08-04-2018       Aarushi         Tamil Nadu             Chennai
49   B-25752  14-08-2018       Vaibhav     Madhya Pradesh              Indore
50   B-25779  12-09-2018          Savi        Maharashtra                Pune
51   B-25603  03-04-2018         Jahan     Madhya Pradesh              Bhopal
52   B-26051  07-03-2018       Parishi        West Bengal             Kolkata
53   B-25653  08-05-2018         Farah           Nagaland              Kohima
54   B-25855  08-11-2018      Abhijeet     Madhya Pradesh              Bhopal
55   B-25762  26-08-2018       Anudeep     Madhya Pradesh              Indore
56   B-25995  04-02-2018        Yohann              Delhi               Delhi
57   B-25929  02-01-2018        Girase            Kerala   Thiruvananthapuram
58   B-26006  09-02-2018        Arpita          Karnataka           Bangalore
59   B-25697  22-06-2018         Vijay  Jammu and Kashmir             Kashmir
60   B-25836  29-10-2018          Arti        Maharashtra                Pune
61   B-25601  01-04-2018        Bharat            Gujarat           Ahmedabad
62   B-25873  23-11-2018       Divyeta     Madhya Pradesh              Indore
63   B-26028  20-02-2018         Manju     Andhra Pradesh           Hyderabad
64   B-25964  20-01-2018         Oshin        Maharashtra                Pune
65   B-25676  01-06-2018       Chandni          Rajasthan              Jaipur
66   B-25839  30-10-2018      Pranjali        West Bengal             Kolkata
67   B-25894  04-12-2018          Monu             Punjab            Amritsar
68   B-25925  29-12-2018        Shruti        Maharashtra              Mumbai
69   B-25953  14-01-2018       Krutika     Andhra Pradesh           Hyderabad
70   B-25772  02-09-2018       Sanjana              Bihar               Patna
71   B-25957  18-01-2018        Mahima     Madhya Pradesh              Indore
72   B-25730  22-07-2018       Rishabh          Rajasthan              Jaipur
73   B-25877  24-11-2018       Dashyam            Gujarat               Surat
74   B-26067  16-03-2018        Tulika     Madhya Pradesh              Bhopal
75   B-25810  10-10-2018       Nripraj             Punjab          Chandigarh
76   B-25868  18-11-2018        Vikash                Goa                 Goa
77   B-26023  19-02-2018        Mukesh            Haryana          Chandigarh
78   B-25626  23-04-2018        Bhishm        Maharashtra              Mumbai
79   B-25937  05-01-2018         Ankit            Haryana          Chandigarh
80   B-25610  09-04-2018        Yogesh              Bihar               Patna
81   B-25777  10-09-2018         Aditi     Madhya Pradesh              Indore
82   B-25738  02-08-2018         Ayush             Punjab          Chandigarh
83   B-25978  27-01-2018         Parin        Maharashtra              Mumbai
84   B-25643  29-04-2018         Kirti  Jammu and Kashmir             Kashmir
85   B-25728  22-07-2018       Ameesha        Maharashtra                Pune
86   B-25749  13-08-2018         Ayush        Maharashtra              Mumbai
87   B-25667  23-05-2018        Anjali            Haryana          Chandigarh
88   B-25657  13-05-2018        Tulika     Madhya Pradesh              Bhopal
89   B-25753  17-08-2018        Shivam      Uttar Pradesh             Lucknow
90   B-26061  14-03-2018        Anurag     Madhya Pradesh              Indore
91   B-25838  29-10-2018       Sanjana     Madhya Pradesh              Indore
92   B-25702  27-06-2018        Shaily        Maharashtra              Mumbai
93   B-25952  13-01-2018      Priyanka     Madhya Pradesh              Indore
94   B-25666  22-05-2018         Tanvi             Punjab          Chandigarh
95   B-25675  31-05-2018        Shreya     Madhya Pradesh              Bhopal
96   B-25650  06-05-2018        Chirag        Maharashtra              Mumbai
97   B-25986  31-01-2018        Shweta          Rajasthan             Udaipur
98   B-25850  05-11-2018      Abhishek                Goa                 Goa
99   B-25898  07-12-2018      Abhishek          Rajasthan             Udaipur
100  B-25813  10-10-2018   Hrisheekesh        Maharashtra              Mumbai
101  B-25825  21-10-2018        Kartik     Madhya Pradesh              Indore
102  B-25954  14-01-2018        Trupti            Gujarat           Ahmedabad
103  B-25696  21-06-2018        Noopur          Karnataka           Bangalore
104  B-25638  26-04-2018         Parth        Maharashtra                Pune
105  B-25747  11-08-2018         Harsh     Madhya Pradesh              Bhopal
106  B-25904  10-12-2018       Swapnil              Delhi               Delhi
107  B-25852  07-11-2018   Soumyabrata     Andhra Pradesh           Hyderabad
108  B-25981  28-01-2018        Amruta              Delhi               Delhi
109  B-25899  08-12-2018     Aishwarya      Uttar Pradesh           Prayagraj
110  B-25870  20-11-2018        Pranav     Andhra Pradesh           Hyderabad
111  B-26040  26-02-2018         Sahil             Punjab          Chandigarh
112  B-25671  27-05-2018        Mitali           Nagaland              Kohima
113  B-26100  31-03-2018        Hitika     Madhya Pradesh              Indore
114  B-25651  07-05-2018        Anurag     Madhya Pradesh              Indore
115  B-25968  21-01-2018      Paromita             Punjab            Amritsar
116  B-26019  15-02-2018        Jitesh      Uttar Pradesh             Lucknow
117  B-25664  20-05-2018   Pratyusmita              Bihar               Patna
118  B-26033  22-02-2018        Atharv        West Bengal             Kolkata
119  B-26052  08-03-2018          Ajay          Karnataka           Bangalore
120  B-25999  05-02-2018       Diwakar              Delhi               Delhi
121  B-25781  14-09-2018        Rutuja            Gujarat           Ahmedabad
122  B-25764  28-08-2018       Sanjova        Maharashtra                Pune
123  B-25803  05-10-2018     Shivanshu     Madhya Pradesh              Indore
124  B-25945  11-01-2018        Mhatre     Madhya Pradesh              Indore
125  B-26086  26-03-2018        Mukesh            Haryana          Chandigarh
126  B-25845  03-11-2018          Snel            Kerala   Thiruvananthapuram
127  B-25817  13-10-2018       Praneet        Maharashtra              Mumbai
128  B-25951  13-01-2018         Jesal        West Bengal             Kolkata
129  B-25970  22-01-2018          Rhea        Maharashtra              Mumbai
130  B-25878  24-11-2018        Mrinal        Maharashtra              Mumbai
131  B-26057  10-03-2018        Sharda            Kerala   Thiruvananthapuram
132  B-25885  28-11-2018       Shatayu     Madhya Pradesh              Indore
133  B-25897  06-12-2018         Rohan     Madhya Pradesh              Indore
134  B-25756  20-08-2018         Mohan        Maharashtra              Mumbai
135  B-25859  14-11-2018        Chikku     Madhya Pradesh              Indore
136  B-25691  16-06-2018       Akancha        Maharashtra              Mumbai
137  B-25633  26-04-2018          Amit             Sikkim             Gangtok
138  B-25708  01-07-2018       Kishwar     Madhya Pradesh              Indore
139  B-25831  27-10-2018        Mahima             Sikkim             Gangtok
140  B-25856  10-11-2018      Abhijeet        Maharashtra              Mumbai
141  B-25893  04-12-2018        Vrinda      Uttar Pradesh             Mathura
142  B-25959  18-01-2018        Muskan     Madhya Pradesh              Indore
143  B-26000  06-02-2018       Shubham              Delhi               Delhi
144  B-26097  28-03-2018          Vini          Karnataka           Bangalore
145  B-25745  09-08-2018        Kartik            Gujarat           Ahmedabad
146  B-25974  25-01-2018       Manisha          Rajasthan             Udaipur
147  B-25670  25-05-2018       Charika                Goa                 Goa
148  B-25848  03-11-2018         Rohan   Himachal Pradesh               Simla
149  B-25888  02-12-2018         Rohan             Punjab            Amritsar
150  B-25942  08-01-2018         Ankur     Andhra Pradesh           Hyderabad
151  B-25847  03-11-2018        Aniket            Haryana          Chandigarh
152  B-25636  26-04-2018         Nishi        Maharashtra              Mumbai
153  B-25826  22-10-2018     Tanushree        Maharashtra              Mumbai
154  B-26081  22-03-2018       Aarushi         Tamil Nadu             Chennai
155  B-25625  23-04-2018         Pinky  Jammu and Kashmir             Kashmir
156  B-25802  05-10-2018          Yash        Maharashtra              Mumbai
157  B-25693  18-06-2018         Parna     Madhya Pradesh              Bhopal
158  B-25796  24-09-2018       Sukrith        Maharashtra              Mumbai
159  B-25806  06-10-2018       Dhanraj     Madhya Pradesh              Indore
160  B-25710  05-07-2018         Megha        Maharashtra                Pune
161  B-25669  25-05-2018        Piyali             Sikkim             Gangtok
162  B-25857  10-11-2018         Anand     Madhya Pradesh              Indore
163  B-25785  15-09-2018         Ayush        West Bengal             Kolkata
164  B-25930  03-01-2018        Monica             Punjab          Chandigarh
165  B-26053  09-03-2018         Kirti  Jammu and Kashmir             Kashmir
166  B-26070  18-03-2018        Shruti          Karnataka           Bangalore
167  B-25791  24-09-2018         Avish            Kerala   Thiruvananthapuram
168  B-25983  30-01-2018          Atul              Delhi               Delhi
169  B-25979  27-01-2018      Shivangi     Madhya Pradesh              Indore
170  B-26054  10-03-2018        Mayank        Maharashtra              Mumbai
171  B-26078  22-03-2018       Kasheen        West Bengal             Kolkata
172  B-25787  20-09-2018         Asish  Jammu and Kashmir             Kashmir
173  B-25682  07-06-2018       Krutika              Bihar               Patna
174  B-25962  19-01-2018     Tejeswini        Maharashtra                Pune
175  B-25750  14-08-2018     Priyanshu     Madhya Pradesh              Indore
176  B-25828  24-10-2018        Nikita             Punjab          Chandigarh
177  B-25622  22-04-2018       Monisha          Rajasthan              Jaipur
178  B-25751  14-08-2018       Nishant        Maharashtra              Mumbai
179  B-25685  10-06-2018       Sheetal     Madhya Pradesh              Indore
180  B-26010  11-02-2018      Kartikay              Bihar               Patna
181  B-26035  23-02-2018         Pinky  Jammu and Kashmir             Kashmir
182  B-25698  23-06-2018        Amisha         Tamil Nadu             Chennai
183  B-25966  21-01-2018        Soumya          Rajasthan             Udaipur
184  B-25832  28-10-2018      Harshita        Maharashtra              Mumbai
185  B-25743  07-08-2018          Aman           Nagaland              Kohima
186  B-25886  28-11-2018       Brijesh          Rajasthan             Udaipur
187  B-25975  25-01-2018      Priyanka      Uttar Pradesh           Prayagraj
188  B-26098  29-03-2018         Pinky  Jammu and Kashmir             Kashmir
189  B-25614  13-04-2018       Vandana   Himachal Pradesh               Simla
190  B-25726  21-07-2018         Kiran        Maharashtra              Mumbai
191  B-26050  06-03-2018       Paridhi          Rajasthan              Jaipur
192  B-25609  09-04-2018        Jitesh      Uttar Pradesh             Lucknow
193  B-25741  03-08-2018       Navdeep     Madhya Pradesh              Indore
194  B-25956  17-01-2018        Shreya        Maharashtra              Mumbai
195  B-25689  14-06-2018   Bhaggyasree        Maharashtra              Mumbai
196  B-25939  05-01-2018        Vineet             Sikkim             Gangtok
197  B-25890  04-12-2018     Divyansha        Maharashtra              Mumbai
198  B-25814  10-10-2018       Swapnil     Madhya Pradesh              Indore
199  B-25718  12-07-2018        Anjali        Maharashtra              Mumbai
200  B-25914  18-12-2018         Kajal              Delhi               Delhi
201  B-25903  10-12-2018         Amlan     Madhya Pradesh              Indore
202  B-26096  28-03-2018        Atharv        West Bengal             Kolkata
203  B-25654  10-05-2018         Sabah        Maharashtra              Mumbai
204  B-26076  21-03-2018         Jahan     Madhya Pradesh              Bhopal
205  B-25961  18-01-2018        Surbhi            Gujarat           Ahmedabad
206  B-25854  08-11-2018       Shubham        Maharashtra                Pune
207  B-25642  28-04-2018          Ajay          Karnataka           Bangalore
208  B-25683  08-06-2018        Shreya            Kerala   Thiruvananthapuram
209  B-26016  14-02-2018         Hazel          Karnataka           Bangalore
210  B-26034  23-02-2018          Vini          Karnataka           Bangalore
211  B-26056  10-03-2018         Sonal              Bihar               Patna
212  B-25819  15-10-2018         Ankur     Madhya Pradesh              Bhopal
213  B-25715  10-07-2018       Srishti  Jammu and Kashmir             Kashmir
214  B-25933  04-01-2018       Shikhar        Maharashtra              Mumbai
215  B-26014  13-02-2018        Divsha          Rajasthan              Jaipur
216  B-25655  11-05-2018          Nida     Madhya Pradesh              Indore
217  B-25816  12-10-2018          Mane     Andhra Pradesh           Hyderabad
218  B-25634  26-04-2018        Sanjay                Goa                 Goa
219  B-25895  04-12-2018        Sathya            Gujarat               Surat
220  B-25687  11-06-2018        Sanjna        Maharashtra              Mumbai
221  B-25662  17-05-2018         Sweta        Maharashtra              Mumbai
222  B-25635  26-04-2018         Nidhi           Nagaland              Kohima
223  B-26060  13-03-2018        Chirag        Maharashtra              Mumbai
224  B-26045  03-03-2018         Nidhi           Nagaland              Kohima
225  B-25770  02-09-2018        Sakshi     Madhya Pradesh              Indore
226  B-25744  08-08-2018      Devendra     Andhra Pradesh           Hyderabad
227  B-25618  18-04-2018         Manju     Andhra Pradesh           Hyderabad
228  B-25958  18-01-2018     Aparajita        West Bengal             Kolkata
229  B-25769  02-09-2018        Surbhi        Maharashtra              Mumbai
230  B-25619  18-04-2018        Ramesh            Gujarat           Ahmedabad
231  B-25688  11-06-2018        Swetha     Madhya Pradesh              Indore
232  B-25829  25-10-2018       Apoorva            Haryana          Chandigarh
233  B-26036  23-02-2018        Bhishm        Maharashtra              Mumbai
234  B-25714  09-07-2018         Stuti          Karnataka           Bangalore
235  B-25989  01-02-2018        Anjali              Delhi               Delhi
236  B-25849  04-11-2018             K             Sikkim             Gangtok
237  B-25851  06-11-2018        Kushal           Nagaland              Kohima
238  B-25782  15-09-2018       Aayushi        Maharashtra              Mumbai
239  B-25621  20-04-2018        Deepak     Madhya Pradesh              Bhopal
240  B-25996  04-02-2018      Prashant              Delhi               Delhi
241  B-25678  03-06-2018       Bathina          Karnataka           Bangalore
242  B-25727  22-07-2018     Turumella     Madhya Pradesh              Indore
243  B-26018  14-02-2018       Aarushi         Tamil Nadu             Chennai
244  B-25760  24-08-2018         Pooja                Goa                 Goa
245  B-25804  05-10-2018       Sudheer          Karnataka           Bangalore
246  B-25754  18-08-2018        Akshay              Bihar               Patna
247  B-26020  16-02-2018        Yogesh              Bihar               Patna
248  B-25640  27-04-2018       Paridhi          Rajasthan              Jaipur
249  B-25789  22-09-2018        Akshay      Uttar Pradesh             Lucknow
250  B-26072  20-03-2018         Sweta        Maharashtra              Mumbai
251  B-26007  09-02-2018       Shubham  Jammu and Kashmir             Kashmir
252  B-26087  26-03-2018       Vandana   Himachal Pradesh               Simla
253  B-25617  17-04-2018         Sagar           Nagaland              Kohima
254  B-25984  30-01-2018         Kajal              Delhi               Delhi

In [20]:
display(df)

    Order ID  Order Date  CustomerName              State                City
0    B-26055  10-03-2018     Harivansh      Uttar Pradesh             Mathura
1    B-25993  03-02-2018        Madhav              Delhi               Delhi
2    B-25973  24-01-2018   Madan Mohan      Uttar Pradesh             Mathura
3    B-25923  27-12-2018         Gopal        Maharashtra              Mumbai
4    B-25757  21-08-2018      Vishakha     Madhya Pradesh              Indore
5    B-25967  21-01-2018        Sudevi      Uttar Pradesh           Prayagraj
6    B-25955  16-01-2018         Shiva        Maharashtra                Pune
7    B-26093  27-03-2018        Sarita        Maharashtra                Pune
8    B-25798  01-10-2018        Shishu     Andhra Pradesh           Hyderabad
9    B-25602  01-04-2018        Vrinda        Maharashtra                Pune
10   B-25858  13-11-2018        Uudhav        Maharashtra              Mumbai
11   B-25969  21-01-2018      Shreyshi            Gujarat               Surat
12   B-26099  30-03-2018        Bhishm        Maharashtra              Mumbai
13   B-25997  04-02-2018        Yogesh        Maharashtra                Pune
14   B-25881  25-11-2018        Lalita      Uttar Pradesh             Mathura
15   B-25761  25-08-2018        Madhav      Uttar Pradesh             Mathura
16   B-25887  01-12-2018      Vishakha      Uttar Pradesh           Prayagraj
17   B-25823  18-10-2018         Rohan        Maharashtra              Mumbai
18   B-25853  08-11-2018        Gaurav            Gujarat           Ahmedabad
19   B-25862  15-11-2018          Amol              Bihar               Patna
20   B-25830  26-10-2018        Aastha   Himachal Pradesh               Simla
21   B-25786  19-09-2018   Madan Mohan      Uttar Pradesh             Mathura
22   B-25686  11-06-2018         Pooja   Himachal Pradesh               Simla
23   B-26022  18-02-2018     Shrichand             Punjab          Chandigarh
24   B-26003  08-02-2018        Hitesh     Madhya Pradesh              Bhopal
25   B-25755  19-08-2018       Shourya            Kerala   Thiruvananthapuram
26   B-25902  10-12-2018      Ishpreet        Maharashtra              Mumbai
27   B-25935  04-01-2018        Sudhir           Nagaland              Kohima
28   B-25797  30-09-2018       Sauptik     Madhya Pradesh              Indore
29   B-25639  27-04-2018         Lisha     Madhya Pradesh              Bhopal
30   B-25681  04-06-2018        Bhawna     Madhya Pradesh              Indore
31   B-25909  13-12-2018         Sujay        Maharashtra                Pune
32   B-25910  14-12-2018           Jay              Delhi               Delhi
33   B-25950  13-01-2018        Shruti     Madhya Pradesh              Indore
34   B-25613  12-04-2018         Mohan            Haryana          Chandigarh
35   B-25919  23-12-2018          Neha          Rajasthan             Udaipur
36   B-25768  01-09-2018     Shreyoshe          Karnataka           Bangalore
37   B-25629  24-04-2018        Hemant            Kerala   Thiruvananthapuram
38   B-25729  22-07-2018     Madhulika     Madhya Pradesh              Bhopal
39   B-25943  09-01-2018       Shardul            Gujarat           Ahmedabad
40   B-25842  02-11-2018       Sheetal        Maharashtra                Pune
41   B-26073  21-03-2018    Pournamasi     Madhya Pradesh              Indore
42   B-25778  11-09-2018       Surabhi        Maharashtra              Mumbai
43   B-25717  12-07-2018       Manshul      Uttar Pradesh             Lucknow
44   B-26085  26-03-2018     Shrichand             Punjab          Chandigarh
45   B-26048  04-03-2018         Parth        Maharashtra                Pune
46   B-25793  24-09-2018     Siddharth     Madhya Pradesh              Indore
47   B-25656  11-05-2018      Priyanka        Maharashtra                Pune
48   B-25608  08-04-2018       Aarushi         Tamil Nadu             Chennai
49   B-25752  14-08-2018       Vaibhav     Madhya Pradesh              Indore
50   B-25779  12-09-2018          Savi        Maharashtra                Pune
51   B-25603  03-04-2018         Jahan     Madhya Pradesh              Bhopal
52   B-26051  07-03-2018       Parishi        West Bengal             Kolkata
53   B-25653  08-05-2018         Farah           Nagaland              Kohima
54   B-25855  08-11-2018      Abhijeet     Madhya Pradesh              Bhopal
55   B-25762  26-08-2018       Anudeep     Madhya Pradesh              Indore
56   B-25995  04-02-2018        Yohann              Delhi               Delhi
57   B-25929  02-01-2018        Girase            Kerala   Thiruvananthapuram
58   B-26006  09-02-2018        Arpita          Karnataka           Bangalore
59   B-25697  22-06-2018         Vijay  Jammu and Kashmir             Kashmir
60   B-25836  29-10-2018          Arti        Maharashtra                Pune
61   B-25601  01-04-2018        Bharat            Gujarat           Ahmedabad
62   B-25873  23-11-2018       Divyeta     Madhya Pradesh              Indore
63   B-26028  20-02-2018         Manju     Andhra Pradesh           Hyderabad
64   B-25964  20-01-2018         Oshin        Maharashtra                Pune
65   B-25676  01-06-2018       Chandni          Rajasthan              Jaipur
66   B-25839  30-10-2018      Pranjali        West Bengal             Kolkata
67   B-25894  04-12-2018          Monu             Punjab            Amritsar
68   B-25925  29-12-2018        Shruti        Maharashtra              Mumbai
69   B-25953  14-01-2018       Krutika     Andhra Pradesh           Hyderabad
70   B-25772  02-09-2018       Sanjana              Bihar               Patna
71   B-25957  18-01-2018        Mahima     Madhya Pradesh              Indore
72   B-25730  22-07-2018       Rishabh          Rajasthan              Jaipur
73   B-25877  24-11-2018       Dashyam            Gujarat               Surat
74   B-26067  16-03-2018        Tulika     Madhya Pradesh              Bhopal
75   B-25810  10-10-2018       Nripraj             Punjab          Chandigarh
76   B-25868  18-11-2018        Vikash                Goa                 Goa
77   B-26023  19-02-2018        Mukesh            Haryana          Chandigarh
78   B-25626  23-04-2018        Bhishm        Maharashtra              Mumbai
79   B-25937  05-01-2018         Ankit            Haryana          Chandigarh
80   B-25610  09-04-2018        Yogesh              Bihar               Patna
81   B-25777  10-09-2018         Aditi     Madhya Pradesh              Indore
82   B-25738  02-08-2018         Ayush             Punjab          Chandigarh
83   B-25978  27-01-2018         Parin        Maharashtra              Mumbai
84   B-25643  29-04-2018         Kirti  Jammu and Kashmir             Kashmir
85   B-25728  22-07-2018       Ameesha        Maharashtra                Pune
86   B-25749  13-08-2018         Ayush        Maharashtra              Mumbai
87   B-25667  23-05-2018        Anjali            Haryana          Chandigarh
88   B-25657  13-05-2018        Tulika     Madhya Pradesh              Bhopal
89   B-25753  17-08-2018        Shivam      Uttar Pradesh             Lucknow
90   B-26061  14-03-2018        Anurag     Madhya Pradesh              Indore
91   B-25838  29-10-2018       Sanjana     Madhya Pradesh              Indore
92   B-25702  27-06-2018        Shaily        Maharashtra              Mumbai
93   B-25952  13-01-2018      Priyanka     Madhya Pradesh              Indore
94   B-25666  22-05-2018         Tanvi             Punjab          Chandigarh
95   B-25675  31-05-2018        Shreya     Madhya Pradesh              Bhopal
96   B-25650  06-05-2018        Chirag        Maharashtra              Mumbai
97   B-25986  31-01-2018        Shweta          Rajasthan             Udaipur
98   B-25850  05-11-2018      Abhishek                Goa                 Goa
99   B-25898  07-12-2018      Abhishek          Rajasthan             Udaipur
100  B-25813  10-10-2018   Hrisheekesh        Maharashtra              Mumbai
101  B-25825  21-10-2018        Kartik     Madhya Pradesh              Indore
102  B-25954  14-01-2018        Trupti            Gujarat           Ahmedabad
103  B-25696  21-06-2018        Noopur          Karnataka           Bangalore
104  B-25638  26-04-2018         Parth        Maharashtra                Pune
105  B-25747  11-08-2018         Harsh     Madhya Pradesh              Bhopal
106  B-25904  10-12-2018       Swapnil              Delhi               Delhi
107  B-25852  07-11-2018   Soumyabrata     Andhra Pradesh           Hyderabad
108  B-25981  28-01-2018        Amruta              Delhi               Delhi
109  B-25899  08-12-2018     Aishwarya      Uttar Pradesh           Prayagraj
110  B-25870  20-11-2018        Pranav     Andhra Pradesh           Hyderabad
111  B-26040  26-02-2018         Sahil             Punjab          Chandigarh
112  B-25671  27-05-2018        Mitali           Nagaland              Kohima
113  B-26100  31-03-2018        Hitika     Madhya Pradesh              Indore
114  B-25651  07-05-2018        Anurag     Madhya Pradesh              Indore
115  B-25968  21-01-2018      Paromita             Punjab            Amritsar
116  B-26019  15-02-2018        Jitesh      Uttar Pradesh             Lucknow
117  B-25664  20-05-2018   Pratyusmita              Bihar               Patna
118  B-26033  22-02-2018        Atharv        West Bengal             Kolkata
119  B-26052  08-03-2018          Ajay          Karnataka           Bangalore
120  B-25999  05-02-2018       Diwakar              Delhi               Delhi
121  B-25781  14-09-2018        Rutuja            Gujarat           Ahmedabad
122  B-25764  28-08-2018       Sanjova        Maharashtra                Pune
123  B-25803  05-10-2018     Shivanshu     Madhya Pradesh              Indore
124  B-25945  11-01-2018        Mhatre     Madhya Pradesh              Indore
125  B-26086  26-03-2018        Mukesh            Haryana          Chandigarh
126  B-25845  03-11-2018          Snel            Kerala   Thiruvananthapuram
127  B-25817  13-10-2018       Praneet        Maharashtra              Mumbai
128  B-25951  13-01-2018         Jesal        West Bengal             Kolkata
129  B-25970  22-01-2018          Rhea        Maharashtra              Mumbai
130  B-25878  24-11-2018        Mrinal        Maharashtra              Mumbai
131  B-26057  10-03-2018        Sharda            Kerala   Thiruvananthapuram
132  B-25885  28-11-2018       Shatayu     Madhya Pradesh              Indore
133  B-25897  06-12-2018         Rohan     Madhya Pradesh              Indore
134  B-25756  20-08-2018         Mohan        Maharashtra              Mumbai
135  B-25859  14-11-2018        Chikku     Madhya Pradesh              Indore
136  B-25691  16-06-2018       Akancha        Maharashtra              Mumbai
137  B-25633  26-04-2018          Amit             Sikkim             Gangtok
138  B-25708  01-07-2018       Kishwar     Madhya Pradesh              Indore
139  B-25831  27-10-2018        Mahima             Sikkim             Gangtok
140  B-25856  10-11-2018      Abhijeet        Maharashtra              Mumbai
141  B-25893  04-12-2018        Vrinda      Uttar Pradesh             Mathura
142  B-25959  18-01-2018        Muskan     Madhya Pradesh              Indore
143  B-26000  06-02-2018       Shubham              Delhi               Delhi
144  B-26097  28-03-2018          Vini          Karnataka           Bangalore
145  B-25745  09-08-2018        Kartik            Gujarat           Ahmedabad
146  B-25974  25-01-2018       Manisha          Rajasthan             Udaipur
147  B-25670  25-05-2018       Charika                Goa                 Goa
148  B-25848  03-11-2018         Rohan   Himachal Pradesh               Simla
149  B-25888  02-12-2018         Rohan             Punjab            Amritsar
150  B-25942  08-01-2018         Ankur     Andhra Pradesh           Hyderabad
151  B-25847  03-11-2018        Aniket            Haryana          Chandigarh
152  B-25636  26-04-2018         Nishi        Maharashtra              Mumbai
153  B-25826  22-10-2018     Tanushree        Maharashtra              Mumbai
154  B-26081  22-03-2018       Aarushi         Tamil Nadu             Chennai
155  B-25625  23-04-2018         Pinky  Jammu and Kashmir             Kashmir
156  B-25802  05-10-2018          Yash        Maharashtra              Mumbai
157  B-25693  18-06-2018         Parna     Madhya Pradesh              Bhopal
158  B-25796  24-09-2018       Sukrith        Maharashtra              Mumbai
159  B-25806  06-10-2018       Dhanraj     Madhya Pradesh              Indore
160  B-25710  05-07-2018         Megha        Maharashtra                Pune
161  B-25669  25-05-2018        Piyali             Sikkim             Gangtok
162  B-25857  10-11-2018         Anand     Madhya Pradesh              Indore
163  B-25785  15-09-2018         Ayush        West Bengal             Kolkata
164  B-25930  03-01-2018        Monica             Punjab          Chandigarh
165  B-26053  09-03-2018         Kirti  Jammu and Kashmir             Kashmir
166  B-26070  18-03-2018        Shruti          Karnataka           Bangalore
167  B-25791  24-09-2018         Avish            Kerala   Thiruvananthapuram
168  B-25983  30-01-2018          Atul              Delhi               Delhi
169  B-25979  27-01-2018      Shivangi     Madhya Pradesh              Indore
170  B-26054  10-03-2018        Mayank        Maharashtra              Mumbai
171  B-26078  22-03-2018       Kasheen        West Bengal             Kolkata
172  B-25787  20-09-2018         Asish  Jammu and Kashmir             Kashmir
173  B-25682  07-06-2018       Krutika              Bihar               Patna
174  B-25962  19-01-2018     Tejeswini        Maharashtra                Pune
175  B-25750  14-08-2018     Priyanshu     Madhya Pradesh              Indore
176  B-25828  24-10-2018        Nikita             Punjab          Chandigarh
177  B-25622  22-04-2018       Monisha          Rajasthan              Jaipur
178  B-25751  14-08-2018       Nishant        Maharashtra              Mumbai
179  B-25685  10-06-2018       Sheetal     Madhya Pradesh              Indore
180  B-26010  11-02-2018      Kartikay              Bihar               Patna
181  B-26035  23-02-2018         Pinky  Jammu and Kashmir             Kashmir
182  B-25698  23-06-2018        Amisha         Tamil Nadu             Chennai
183  B-25966  21-01-2018        Soumya          Rajasthan             Udaipur
184  B-25832  28-10-2018      Harshita        Maharashtra              Mumbai
185  B-25743  07-08-2018          Aman           Nagaland              Kohima
186  B-25886  28-11-2018       Brijesh          Rajasthan             Udaipur
187  B-25975  25-01-2018      Priyanka      Uttar Pradesh           Prayagraj
188  B-26098  29-03-2018         Pinky  Jammu and Kashmir             Kashmir
189  B-25614  13-04-2018       Vandana   Himachal Pradesh               Simla
190  B-25726  21-07-2018         Kiran        Maharashtra              Mumbai
191  B-26050  06-03-2018       Paridhi          Rajasthan              Jaipur
192  B-25609  09-04-2018        Jitesh      Uttar Pradesh             Lucknow
193  B-25741  03-08-2018       Navdeep     Madhya Pradesh              Indore
194  B-25956  17-01-2018        Shreya        Maharashtra              Mumbai
195  B-25689  14-06-2018   Bhaggyasree        Maharashtra              Mumbai
196  B-25939  05-01-2018        Vineet             Sikkim             Gangtok
197  B-25890  04-12-2018     Divyansha        Maharashtra              Mumbai
198  B-25814  10-10-2018       Swapnil     Madhya Pradesh              Indore
199  B-25718  12-07-2018        Anjali        Maharashtra              Mumbai
200  B-25914  18-12-2018         Kajal              Delhi               Delhi
201  B-25903  10-12-2018         Amlan     Madhya Pradesh              Indore
202  B-26096  28-03-2018        Atharv        West Bengal             Kolkata
203  B-25654  10-05-2018         Sabah        Maharashtra              Mumbai
204  B-26076  21-03-2018         Jahan     Madhya Pradesh              Bhopal
205  B-25961  18-01-2018        Surbhi            Gujarat           Ahmedabad
206  B-25854  08-11-2018       Shubham        Maharashtra                Pune
207  B-25642  28-04-2018          Ajay          Karnataka           Bangalore
208  B-25683  08-06-2018        Shreya            Kerala   Thiruvananthapuram
209  B-26016  14-02-2018         Hazel          Karnataka           Bangalore
210  B-26034  23-02-2018          Vini          Karnataka           Bangalore
211  B-26056  10-03-2018         Sonal              Bihar               Patna
212  B-25819  15-10-2018         Ankur     Madhya Pradesh              Bhopal
213  B-25715  10-07-2018       Srishti  Jammu and Kashmir             Kashmir
214  B-25933  04-01-2018       Shikhar        Maharashtra              Mumbai
215  B-26014  13-02-2018        Divsha          Rajasthan              Jaipur
216  B-25655  11-05-2018          Nida     Madhya Pradesh              Indore
217  B-25816  12-10-2018          Mane     Andhra Pradesh           Hyderabad
218  B-25634  26-04-2018        Sanjay                Goa                 Goa
219  B-25895  04-12-2018        Sathya            Gujarat               Surat
220  B-25687  11-06-2018        Sanjna        Maharashtra              Mumbai
221  B-25662  17-05-2018         Sweta        Maharashtra              Mumbai
222  B-25635  26-04-2018         Nidhi           Nagaland              Kohima
223  B-26060  13-03-2018        Chirag        Maharashtra              Mumbai
224  B-26045  03-03-2018         Nidhi           Nagaland              Kohima
225  B-25770  02-09-2018        Sakshi     Madhya Pradesh              Indore
226  B-25744  08-08-2018      Devendra     Andhra Pradesh           Hyderabad
227  B-25618  18-04-2018         Manju     Andhra Pradesh           Hyderabad
228  B-25958  18-01-2018     Aparajita        West Bengal             Kolkata
229  B-25769  02-09-2018        Surbhi        Maharashtra              Mumbai
230  B-25619  18-04-2018        Ramesh            Gujarat           Ahmedabad
231  B-25688  11-06-2018        Swetha     Madhya Pradesh              Indore
232  B-25829  25-10-2018       Apoorva            Haryana          Chandigarh
233  B-26036  23-02-2018        Bhishm        Maharashtra              Mumbai
234  B-25714  09-07-2018         Stuti          Karnataka           Bangalore
235  B-25989  01-02-2018        Anjali              Delhi               Delhi
236  B-25849  04-11-2018             K             Sikkim             Gangtok
237  B-25851  06-11-2018        Kushal           Nagaland              Kohima
238  B-25782  15-09-2018       Aayushi        Maharashtra              Mumbai
239  B-25621  20-04-2018        Deepak     Madhya Pradesh              Bhopal
240  B-25996  04-02-2018      Prashant              Delhi               Delhi
241  B-25678  03-06-2018       Bathina          Karnataka           Bangalore
242  B-25727  22-07-2018     Turumella     Madhya Pradesh              Indore
243  B-26018  14-02-2018       Aarushi         Tamil Nadu             Chennai
244  B-25760  24-08-2018         Pooja                Goa                 Goa
245  B-25804  05-10-2018       Sudheer          Karnataka           Bangalore
246  B-25754  18-08-2018        Akshay              Bihar               Patna
247  B-26020  16-02-2018        Yogesh              Bihar               Patna
248  B-25640  27-04-2018       Paridhi          Rajasthan              Jaipur
249  B-25789  22-09-2018        Akshay      Uttar Pradesh             Lucknow
250  B-26072  20-03-2018         Sweta        Maharashtra              Mumbai
251  B-26007  09-02-2018       Shubham  Jammu and Kashmir             Kashmir
252  B-26087  26-03-2018       Vandana   Himachal Pradesh               Simla
253  B-25617  17-04-2018         Sagar           Nagaland              Kohima
254  B-25984  30-01-2018         Kajal              Delhi               Delhi

In [28]:
df[df["City"].str.endswith("d")]

    Order ID  Order Date CustomerName           State       City
8    B-25798  01-10-2018       Shishu  Andhra Pradesh  Hyderabad
18   B-25853  08-11-2018       Gaurav         Gujarat  Ahmedabad
39   B-25943  09-01-2018      Shardul         Gujarat  Ahmedabad
61   B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
63   B-26028  20-02-2018        Manju  Andhra Pradesh  Hyderabad
69   B-25953  14-01-2018      Krutika  Andhra Pradesh  Hyderabad
102  B-25954  14-01-2018       Trupti         Gujarat  Ahmedabad
107  B-25852  07-11-2018  Soumyabrata  Andhra Pradesh  Hyderabad
110  B-25870  20-11-2018       Pranav  Andhra Pradesh  Hyderabad
121  B-25781  14-09-2018       Rutuja         Gujarat  Ahmedabad
145  B-25745  09-08-2018       Kartik         Gujarat  Ahmedabad
150  B-25942  08-01-2018        Ankur  Andhra Pradesh  Hyderabad
205  B-25961  18-01-2018       Surbhi         Gujarat  Ahmedabad
217  B-25816  12-10-2018         Mane  Andhra Pradesh  Hyderabad
226  B-25744  08-08-2018     Devendra  Andhra Pradesh  Hyderabad
227  B-25618  18-04-2018        Manju  Andhra Pradesh  Hyderabad
230  B-25619  18-04-2018       Ramesh         Gujarat  Ahmedabad
260  B-25947  13-01-2018       Chetan         Gujarat  Ahmedabad
291  B-25799  01-10-2018     Divyansh         Gujarat  Ahmedabad
310  B-25960  18-01-2018       Shreya  Andhra Pradesh  Hyderabad
323  B-26091  27-03-2018        Manju  Andhra Pradesh  Hyderabad
326  B-25835  29-10-2018      Moumita         Gujarat  Ahmedabad
338  B-25946  12-01-2018      Saurabh  Andhra Pradesh  Hyderabad
343  B-25673  28-05-2018      Arsheen         Gujarat  Ahmedabad
349  B-25780  13-09-2018        Teena  Andhra Pradesh  Hyderabad
392  B-26092  27-03-2018       Ramesh         Gujarat  Ahmedabad
396  B-26011  12-02-2018       Bharat         Gujarat  Ahmedabad
429  B-25763  27-08-2018      Noshiba         Gujarat  Ahmedabad
433  B-26074  21-03-2018       Bharat         Gujarat  Ahmedabad
473  B-25672  28-05-2018     Akanksha  Andhra Pradesh  Hyderabad
480  B-26029  20-02-2018       Ramesh         Gujarat  Ahmedabad
491  B-25834  29-10-2018       Ananya  Andhra Pradesh  Hyderabad

In [29]:
df[df["City"].str.startswith("I")]

    Order ID  Order Date CustomerName           State    City
4    B-25757  21-08-2018     Vishakha  Madhya Pradesh  Indore
28   B-25797  30-09-2018      Sauptik  Madhya Pradesh  Indore
30   B-25681  04-06-2018       Bhawna  Madhya Pradesh  Indore
33   B-25950  13-01-2018       Shruti  Madhya Pradesh  Indore
41   B-26073  21-03-2018   Pournamasi  Madhya Pradesh  Indore
46   B-25793  24-09-2018    Siddharth  Madhya Pradesh  Indore
49   B-25752  14-08-2018      Vaibhav  Madhya Pradesh  Indore
55   B-25762  26-08-2018      Anudeep  Madhya Pradesh  Indore
62   B-25873  23-11-2018      Divyeta  Madhya Pradesh  Indore
71   B-25957  18-01-2018       Mahima  Madhya Pradesh  Indore
81   B-25777  10-09-2018        Aditi  Madhya Pradesh  Indore
90   B-26061  14-03-2018       Anurag  Madhya Pradesh  Indore
91   B-25838  29-10-2018      Sanjana  Madhya Pradesh  Indore
93   B-25952  13-01-2018     Priyanka  Madhya Pradesh  Indore
101  B-25825  21-10-2018       Kartik  Madhya Pradesh  Indore
113  B-26100  31-03-2018       Hitika  Madhya Pradesh  Indore
114  B-25651  07-05-2018       Anurag  Madhya Pradesh  Indore
123  B-25803  05-10-2018    Shivanshu  Madhya Pradesh  Indore
124  B-25945  11-01-2018       Mhatre  Madhya Pradesh  Indore
132  B-25885  28-11-2018      Shatayu  Madhya Pradesh  Indore
133  B-25897  06-12-2018        Rohan  Madhya Pradesh  Indore
135  B-25859  14-11-2018       Chikku  Madhya Pradesh  Indore
138  B-25708  01-07-2018      Kishwar  Madhya Pradesh  Indore
142  B-25959  18-01-2018       Muskan  Madhya Pradesh  Indore
159  B-25806  06-10-2018      Dhanraj  Madhya Pradesh  Indore
162  B-25857  10-11-2018        Anand  Madhya Pradesh  Indore
169  B-25979  27-01-2018     Shivangi  Madhya Pradesh  Indore
175  B-25750  14-08-2018    Priyanshu  Madhya Pradesh  Indore
179  B-25685  10-06-2018      Sheetal  Madhya Pradesh  Indore
193  B-25741  03-08-2018      Navdeep  Madhya Pradesh  Indore
198  B-25814  10-10-2018      Swapnil  Madhya Pradesh  Indore
201  B-25903  10-12-2018        Amlan  Madhya Pradesh  Indore
216  B-25655  11-05-2018         Nida  Madhya Pradesh  Indore
225  B-25770  02-09-2018       Sakshi  Madhya Pradesh  Indore
231  B-25688  11-06-2018       Swetha  Madhya Pradesh  Indore
242  B-25727  22-07-2018    Turumella  Madhya Pradesh  Indore
258  B-25663  19-05-2018   Pournamasi  Madhya Pradesh  Indore
267  B-25645  01-05-2018       Yaanvi  Madhya Pradesh  Indore
270  B-25812  10-10-2018      Kshitij  Madhya Pradesh  Indore
276  B-25918  22-12-2018    Karandeep  Madhya Pradesh  Indore
277  B-25971  22-01-2018       Mitali  Madhya Pradesh  Indore
280  B-25703  28-06-2018         Ekta  Madhya Pradesh  Indore
293  B-25985  31-01-2018        Ginny  Madhya Pradesh  Indore
301  B-25991  03-02-2018        Mansi  Madhya Pradesh  Indore
302  B-25737  01-08-2018      Shubham  Madhya Pradesh  Indore
311  B-26037  23-02-2018       Hitika  Madhya Pradesh  Indore
314  B-25724  19-07-2018      Sheetal  Madhya Pradesh  Indore
325  B-25827  23-10-2018      Sheetal  Madhya Pradesh  Indore
339  B-26065  16-03-2018         Nida  Madhya Pradesh  Indore
344  B-25692  17-06-2018       Rashmi  Madhya Pradesh  Indore
367  B-25891  04-12-2018      Shivani  Madhya Pradesh  Indore
371  B-25637  26-04-2018        Ashmi  Madhya Pradesh  Indore
378  B-25734  29-07-2018       Pranav  Madhya Pradesh  Indore
380  B-25934  04-01-2018        Rahul  Madhya Pradesh  Indore
383  B-25824  20-10-2018        Shyam  Madhya Pradesh  Indore
391  B-25701  26-06-2018    Maithilee  Madhya Pradesh  Indore
394  B-25818  14-10-2018      Sandeep  Madhya Pradesh  Indore
401  B-25844  03-11-2018        Swati  Madhya Pradesh  Indore
404  B-25865  15-11-2018         Arun  Madhya Pradesh  Indore
416  B-25680  04-06-2018      Aayushi  Madhya Pradesh  Indore
418  B-25932  04-01-2018     Bhutekar  Madhya Pradesh  Indore
423  B-25833  29-10-2018      Krishna  Madhya Pradesh  Indore
431  B-25879  24-11-2018    Siddharth  Madhya Pradesh  Indore
432  B-25926  30-12-2018       Dipali  Madhya Pradesh  Indore
434  B-25627  23-04-2018       Hitika  Madhya Pradesh  Indore
436  B-26047  04-03-2018        Ashmi  Madhya Pradesh  Indore
449  B-25705  30-06-2018       Shweta  Madhya Pradesh  Indore
454  B-25709  01-07-2018    Aakanksha  Madhya Pradesh  Indore
461  B-25783  15-09-2018     Shivangi  Madhya Pradesh  Indore
463  B-25690  15-06-2018       Gunjan  Madhya Pradesh  Indore
468  B-25719  12-07-2018       Rashmi  Madhya Pradesh  Indore

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Orders.csv")

In [6]:
df[df["City"]=="Mathura"]

    Order ID  Order Date CustomerName          State     City
0    B-26055  10-03-2018    Harivansh  Uttar Pradesh  Mathura
2    B-25973  24-01-2018  Madan Mohan  Uttar Pradesh  Mathura
14   B-25881  25-11-2018       Lalita  Uttar Pradesh  Mathura
15   B-25761  25-08-2018       Madhav  Uttar Pradesh  Mathura
21   B-25786  19-09-2018  Madan Mohan  Uttar Pradesh  Mathura
141  B-25893  04-12-2018       Vrinda  Uttar Pradesh  Mathura

In [5]:
(df["City"]=="Mathura") | (df["City"]=="Delhi")

0       True
1       True
2       True
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: City, Length: 500, dtype: bool

In [7]:
bc=pd.read_csv("train.csv")

In [8]:
bc=bc.drop(columns=['contry_of_res','ID','result'])

In [13]:
for col in bc.columns:
    if bc[col].dtype == 'object':
        bc[col] = pd.Categorical(df[col]).codes
    elif bc[col].dtype == 'float64' or bc[col].dtype == 'int64':
        bc[col] = bc[col].astype(int)

In [14]:
print(bc)

     A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           1         0         1         0         1         0         1
1           0         0         0         0         0         0         0
2           1         1         1         1         1         1         1
3           0         0         0         0         0         0         0
4           0         0         0         0         0         0         0
..        ...       ...       ...       ...       ...       ...       ...
795         0         1         0         0         0         0         0
796         0         1         1         0         0         1         0
797         0         0         0         0         0         0         0
798         0         0         0         0         0         0         0
799         0         1         0         0         0         0         0

     A8_Score  A9_Score  A10_Score  age gender       ethnicity jaundice  \
0           0         1          1   38      f               ?       no
1           0         0          0   47      m               ?       no
2           1         1          1    7      m  White-European       no
3           0         0          0   23      f               ?       no
4           0         0          0   43      m               ?       no
..        ...       ...        ...  ...    ...             ...      ...
795         0         1          1   16      m        Hispanic       no
796         1         1          1   20      m  White-European       no
797         0         0          0    5      m     South Asian      yes
798         0         0          0   16      f               ?       no
799         0         0          0   46      f               ?       no

    austim used_app_before     age_desc relation  Class/ASD
0       no              no  18 and more     Self          0
1       no              no  18 and more     Self          0
2      yes              no  18 and more     Self          1
3       no              no  18 and more     Self          0
4       no              no  18 and more     Self          0
..     ...             ...          ...      ...        ...
795     no              no  18 and more     Self          0
796     no              no  18 and more     Self          0
797     no              no  18 and more     Self          0
798     no              no  18 and more     Self          0
799     no             yes  18 and more     Self          0

[800 rows x 19 columns]

In [1]:
df.rename(column=("CustomerName:Customer_Name"),inplace=True)

NameError: name 'df' is not defined

In [7]:
df.groupby("City")["Order ID"].sum()

NameError: name 'df' is not defined